In [1]:
import KNN
import numpy as np
import pandas as pd

In [2]:
class1=pd.read_csv('class1Train.csv').drop('Unnamed: 0',axis=1)
class2=pd.read_csv('class2Train.csv').drop('Unnamed: 0',axis=1)
class3=pd.read_csv('class3Train.csv').drop('Unnamed: 0',axis=1)

In [3]:
class1['label'] =1 
class2['label'] =2 
class3['label'] = 3

In [4]:
class1_t=pd.read_csv('class1Test.csv').drop('Unnamed: 0',axis=1)
class2_t=pd.read_csv('class2Test.csv').drop('Unnamed: 0',axis=1)
class3_t=pd.read_csv('class3Test.csv').drop('Unnamed: 0',axis=1)

In [5]:
class1_t['label'] =1 
class2_t['label'] =2 
class3_t['label'] =3

In [6]:
combined_data_test = pd.concat([class1_t, class2_t, class3_t], ignore_index=True)
x = combined_data_test[['x', 'y']].values 
y_true=combined_data_test['label'].values   

In [7]:
combined_data = pd.concat([class1, class2, class3], ignore_index=True)
X = combined_data[['x', 'y']].values 
y = combined_data['label'].values   

X

array([[19.094  ,  1.5685 ],
       [17.546  ,  0.1327 ],
       [17.262  , -1.0689 ],
       ...,
       [ 0.30742,  1.2562 ],
       [-2.4449 ,  1.8622 ],
       [-2.261  ,  3.5515 ]])

In [8]:
X.shape

(1050, 2)

In [9]:
knn = KNN.KNN(k=9)
knn.fit(X, y)
knn.plot_decision_boundary(X, y)

In [10]:
final_pred=pd.DataFrame(x,columns=['x1','x2'])
final_pred['y_cap']=knn.predict(x)
final_pred

x1       x2  y_cap
0    14.236000 -0.42192      1
1    15.517000 -0.45230      1
2     8.562100 -1.54380      1
3    13.156000 -0.55674      1
4    16.515000  0.81528      1
..         ...      ...    ...
445  -0.089535  0.27791      3
446   0.641320  9.12650      3
447  -0.684390 -2.17840      3
448  -4.344000  4.98280      3
449  -2.820400 -2.14990      3

[450 rows x 3 columns]

In [11]:
f=final_pred[['x1','x2']].values
y_hat=final_pred['y_cap'].values

In [12]:
y_hat

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,

In [13]:
import accuracy

In [14]:
acc=accuracy.accuracy(y_true,y_hat)
acc.accu_percent()

100.0

In [15]:
acc.confusion_matrix()

array([[  0,   0,   0,   0],
       [  0, 150,   0,   0],
       [  0,   0, 150,   0],
       [  0,   0,   0, 150]])

In [16]:
acc.precision()

Precision for class 1 is
1.0
Precision for class 2 is
1.0
Precision for class 3 is
1.0


[1.0, 1.0, 1.0]

In [17]:
acc.recall()

Recall for class1 is 
1.0
Recall for class2 is 
1.0
Recall for class3 is 
1.0


[1.0, 1.0, 1.0]

In [18]:
acc.f_score()

Precision for class 1 is
1.0
Precision for class 2 is
1.0
Precision for class 3 is
1.0
Recall for class1 is 
1.0
Recall for class2 is 
1.0
Recall for class3 is 
1.0
F-score for class 1 is 1.0
F-score for class 2 is 1.0
F-score for class 3 is 1.0


[1.0, 1.0, 1.0]